resources:
- repo: self

trigger: none

jobs:
- job: MySQLRegression
  displayName: MySQLRegression

  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.10'
    inputs:
      versionSpec: 3.10
  - bash: |
      git clone https://github.com/Azure/azure-cli.git
      git branch
      cd azure-cli
      pwd
    displayName: 'git clone azure-cli'
  - bash: |
      set -ev
      python -m venv env
      chmod +x env/bin/activate
      . env/bin/activate
      python -m pip install -U pip
      pip install azdev
      azdev --version
      azdev setup -c . --debug
    displayName: 'azdev setup'
  - bash: |
      set -ev
      . env/bin/activate
      azdev test --live --no-exitfirst test_rdbms_flexible_commands --mark mysql_regression

    displayName: 'azdev test rdbms'